### PR TITLE
Fix issue-124 (KOR/PRK mix up)

### PR DESCRIPTION
**Pull request by lukaszgajewski**
Fixes this issue: #124 .
I'm proposing a simple patch on the final import script to swap the ISO codes _where needed_.
Alternatively we could fix the xls file manually perhaps?
Can we add some sanity checks/tests based on our expectations of what the values should be?
For example, population -- we can simply assert Population(KOR) >  Population(PRK).
Not sure whether other columns are as easy, though.

### CODE REVIEW

**Comment by lukaszgajewski** [comment]
Good catch, @simonblouin . This was due to the misaligned of code/names in ImportUtilities.
Had to rerun some of the other scripts, including the ones failing as mentioned in #139 so this PR now also fixes that.

**Comment by lukaszgajewski** [comment]
So, the only thing that's failing right now is "Permission to allfed/allfed-integrated-model.git denied to github-actions[bot]." on the docs check.
Any ideas on how to fix this @morganrivers ?
We can also ignore it and merge anyway.

**Comment by morganrivers** [comment]
I believe that the main branch fails if there is a "force" in the mkdocs or the push.

I removed these, and also added a github username and email to the bot that was doing the pushing. I also enforced it to wait for the "Running Tests"
So in `docs.yml`:
```
    needs: Running Tests # This ensures docs job runs after the 'Running Tests' job in the Tests workflow
...
          mkdocs gh-deploy --clean --verbose # removed force here
...
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          # removed the "force" here

```

But I had to make a new branch and get your pull request and make a separate one with it.

The PR #155 is thus identical and all tests pass

I think it's fine, all tests passed although I don't see documentation generated anywhere (which is weird because I didn't remove the documentation step).

**Comment by morganrivers** [comment]
so I suggest you either merge in the other one (#155 ), confirm with me that I merge in the other one, or make the changes I made to the other one (#155 ), and if your tests all pass we can merge this in, whatever you prefer

**Comment by lukaszgajewski** [comment]
Probably makes more sense to merge #155  if that one is working and includes the changes here.
Would be great to also include change to Python 3.12.4 though

**Pull request merged**
